# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/tool/vivado/master/cdp_ede_local-master/cdp_ede_local-master/mycpu_env/soc_verify/soc_dram/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/tool/vivado/master/cdp_ede_local-master/cdp_ede_local-master/mycpu_env/soc_verify/soc_dram/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/tool/vivado/master/cdp_ede_local-master/cdp_ede_local-master/mycpu_env/soc_verify/soc_dram/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/tool/vivado/master/cdp_ede_local-master/cdp_ede_local-master/mycpu_env/soc_verify/soc_dram/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
